// MojoBoost — mods-data.js
// Complete mod database

const MODS_DB = [
  {
    id: "sodium",
    name: "Sodium",
    icon: "⚡",
    shortDesc: "The gold standard rendering engine replacement. Massive FPS gains on all devices.",
    description: "Sodium is a free and open-source rendering engine replacement for the Minecraft client that greatly improves frame rates and fixes graphical issues. It replaces Minecraft's built-in chunk rendering pipeline with a modern, optimized one that can achieve 2–5× higher frame rates on the same hardware.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "NeoForge"],
    category: "rendering",
    performanceRating: 98,
    memoryUsage: "low",
    memoryMB: -64,
    fpsGain: { min: 80, max: 300, avg: 150 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 99,
    downloadUrl: "https://modrinth.com/mod/sodium",
    installInstructions: "Download the .jar from Modrinth and place it in your .minecraft/mods folder. Requires Fabric or Quilt loader.",
    tags: ["rendering", "fps", "performance", "essential"],
    featured: true,
    dependencies: ["Fabric API"]
  },
  {
    id: "lithium",
    name: "Lithium",
    icon: "🔋",
    shortDesc: "Game logic and server-side optimizations. Reduces CPU overhead significantly.",
    description: "Lithium is a general-purpose optimization mod for Minecraft which works to improve a number of systems (game physics, mob AI, block ticking, etc.) without changing any behavior. It targets the server-side simulation, making both singleplayer and multiplayer smoother.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "logic",
    performanceRating: 85,
    memoryUsage: "low",
    memoryMB: -32,
    fpsGain: { min: 10, max: 40, avg: 20 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 95,
    downloadUrl: "https://modrinth.com/mod/lithium",
    installInstructions: "Download from Modrinth. Works alongside Sodium. No configuration needed — improvements are automatic.",
    tags: ["logic", "cpu", "performance", "essential"],
    featured: true,
    dependencies: ["Fabric API"]
  },
  {
    id: "ferritecore",
    name: "FerriteCore",
    icon: "🧲",
    shortDesc: "Dramatically reduces memory usage. Essential for low-RAM Android devices.",
    description: "FerriteCore reduces the memory usage of Minecraft in a number of different ways. Some of these changes also improve the game's frame rate, but its primary goal is to reduce memory consumption — often by 500 MB to 1 GB. Absolutely essential for devices with 2–4 GB RAM.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "Forge", "NeoForge"],
    category: "memory",
    performanceRating: 90,
    memoryUsage: "very-low",
    memoryMB: -512,
    fpsGain: { min: 5, max: 30, avg: 15 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 93,
    downloadUrl: "https://modrinth.com/mod/ferrite-core",
    installInstructions: "Drop the .jar in your mods folder. Works with Fabric, Forge, and NeoForge. Reduces RAM usage immediately on launch.",
    tags: ["memory", "ram", "performance", "essential", "mobile"],
    featured: true,
    dependencies: ["Fabric API"]
  },
  {
    id: "modernfix",
    name: "ModernFix",
    icon: "🔧",
    shortDesc: "Fixes dozens of performance bugs. Faster world loading and startup times.",
    description: "ModernFix is an all-in-one mod that improves performance, reduces memory usage, and fixes many bugs in modern Minecraft versions. It speeds up game startup, world loading, and chunk generation while also patching memory leaks and other performance issues introduced in newer Minecraft versions.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Forge", "NeoForge"],
    category: "general",
    performanceRating: 88,
    memoryUsage: "low",
    memoryMB: -256,
    fpsGain: { min: 15, max: 60, avg: 30 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 88,
    downloadUrl: "https://modrinth.com/mod/modernfix",
    installInstructions: "Place in mods folder. Configuration available via ModernFix's config file to enable/disable specific fixes.",
    tags: ["general", "startup", "memory", "essential"],
    featured: true,
    dependencies: ["Fabric API"]
  },
  {
    id: "immediatelyfast",
    name: "ImmediatelyFast",
    icon: "⚡",
    shortDesc: "Optimizes immediate-mode rendering. Huge gains in UI and entity rendering.",
    description: "ImmediatelyFast is a mod that improves the immediate-mode rendering performance of Minecraft. It optimizes how entities, GUI elements, and other objects are rendered using immediate-mode rendering, which is heavily used in Minecraft. Works great alongside Sodium.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "NeoForge"],
    category: "rendering",
    performanceRating: 82,
    memoryUsage: "low",
    memoryMB: -16,
    fpsGain: { min: 20, max: 80, avg: 40 },
    compatibility: { arm64: true, arm32: false, x86: true },
    minAndroid: 10,
    minRAM: 2,
    goals: ["Maximum FPS", "Balanced", "Best Graphics"],
    popularity: 85,
    downloadUrl: "https://modrinth.com/mod/immediatelyfast",
    installInstructions: "Requires Sodium on Fabric. Drop in mods folder. Best combined with Sodium + Lithium for maximum effect.",
    tags: ["rendering", "entities", "gui", "fps"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "entityculling",
    name: "EntityCulling",
    icon: "👁️",
    shortDesc: "Skips rendering entities you can't see. Massive FPS boost in populated areas.",
    description: "EntityCulling uses async path-tracing to determine which entities are visible. Hidden entities (behind walls, underground, etc.) are skipped entirely during rendering. This provides enormous FPS gains in areas with many entities, mobs, or players.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "Forge", "NeoForge"],
    category: "rendering",
    performanceRating: 87,
    memoryUsage: "low",
    memoryMB: -8,
    fpsGain: { min: 15, max: 100, avg: 35 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 86,
    downloadUrl: "https://modrinth.com/mod/entityculling",
    installInstructions: "Place in mods folder. Works on Fabric and Forge. Configuration available for culling aggressiveness.",
    tags: ["rendering", "entities", "culling", "fps"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "dynamicfps",
    name: "Dynamic FPS",
    icon: "🔋",
    shortDesc: "Reduces FPS when game is unfocused. Saves battery life on mobile.",
    description: "Dynamic FPS automatically reduces Minecraft's frame rate when the app is not in focus, and can completely pause rendering when minimized. This saves significant battery life on Android devices, making it an essential mod for mobile Minecraft players.",
    versions: ["1.14", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "battery",
    performanceRating: 75,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 0, max: 10, avg: 5 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Battery Saver", "Balanced"],
    popularity: 80,
    downloadUrl: "https://modrinth.com/mod/dynamic-fps",
    installInstructions: "Drop in mods folder. Configure idle FPS limit in the mod's config. Recommended: 1 FPS when minimized, 30 when unfocused.",
    tags: ["battery", "mobile", "background", "power"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "noisium",
    name: "Noisium",
    icon: "🌍",
    shortDesc: "Speeds up world generation noise calculations. Faster chunk loading.",
    description: "Noisium optimizes world generation by speeding up the noise calculations used to generate terrain. This results in significantly faster chunk loading and world generation, particularly noticeable when exploring new areas or generating new worlds.",
    versions: ["1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "worldgen",
    performanceRating: 78,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 5, max: 25, avg: 12 },
    compatibility: { arm64: true, arm32: false, x86: true },
    minAndroid: 10,
    minRAM: 2,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 72,
    downloadUrl: "https://modrinth.com/mod/noisium",
    installInstructions: "Place in mods folder on Fabric or Quilt. Most noticeable improvement when generating new chunks in 1.20+.",
    tags: ["worldgen", "chunks", "terrain", "loading"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "krypton",
    name: "Krypton",
    icon: "🌐",
    shortDesc: "Optimizes Minecraft's networking stack. Lower latency, better multiplayer.",
    description: "Krypton is a Fabric mod that attempts to optimize the Minecraft networking stack. It includes several optimizations including network I/O improvements and packet compression, which reduces server latency and improves multiplayer performance.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "network",
    performanceRating: 70,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 2, max: 15, avg: 8 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 76,
    downloadUrl: "https://modrinth.com/mod/krypton",
    installInstructions: "Drop in mods folder. Works server-side too for best results. No configuration required.",
    tags: ["network", "multiplayer", "latency", "performance"],
    featured: false,
    dependencies: []
  },
  {
    id: "memoryleakfix",
    name: "Memory Leak Fix",
    icon: "🩹",
    shortDesc: "Patches known Minecraft memory leaks. Prevents crashes on long sessions.",
    description: "Memory Leak Fix patches several known memory leaks in Minecraft that cause the game to use progressively more RAM over time. Without this mod, long gaming sessions can result in crashes due to out-of-memory errors, particularly problematic on Android devices with limited RAM.",
    versions: ["1.14", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "Forge", "NeoForge"],
    category: "memory",
    performanceRating: 83,
    memoryUsage: "very-low",
    memoryMB: -128,
    fpsGain: { min: 5, max: 20, avg: 10 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 84,
    downloadUrl: "https://modrinth.com/mod/memoryleakfix",
    installInstructions: "Place in mods folder. Essential for long gaming sessions. Works across all major mod loaders.",
    tags: ["memory", "ram", "stability", "crashes", "mobile"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "c2me",
    name: "C2ME",
    icon: "🔄",
    shortDesc: "Concurrent Chunk Management Engine. Parallel chunk loading on multi-core CPUs.",
    description: "C2ME (Concurrent Chunk Management Engine) is designed to improve the performance of chunk loading by making chunk loading happen in parallel across multiple CPU cores. This is especially beneficial for devices with multi-core processors, making chunk loading much faster.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "worldgen",
    performanceRating: 80,
    memoryUsage: "medium",
    memoryMB: 64,
    fpsGain: { min: 10, max: 50, avg: 25 },
    compatibility: { arm64: true, arm32: false, x86: true },
    minAndroid: 10,
    minRAM: 3,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 77,
    downloadUrl: "https://modrinth.com/mod/c2me-fabric",
    installInstructions: "Requires at least 3 GB RAM allocation and a multi-core CPU. Drop in mods folder. May cause issues with some chunk-modifying mods.",
    tags: ["chunks", "multicore", "cpu", "loading"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "moreculling",
    name: "More Culling",
    icon: "🎯",
    shortDesc: "Advanced block face and leaf culling. Reduces draw calls significantly.",
    description: "More Culling is a mod that changes how block face and foliage culling works in Minecraft. By more aggressively culling faces and leaves that are not visible to the player, it reduces the number of draw calls and polygons rendered, leading to improved FPS especially in dense forests.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 79,
    memoryUsage: "low",
    memoryMB: -16,
    fpsGain: { min: 10, max: 40, avg: 20 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 9,
    minRAM: 2,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 74,
    downloadUrl: "https://modrinth.com/mod/moreculling",
    installInstructions: "Requires Fabric or Quilt with Fabric API. Place in mods folder. Works best alongside Sodium.",
    tags: ["rendering", "culling", "blocks", "fps"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "enhancedblockentities",
    name: "Enhanced Block Entities",
    icon: "📦",
    shortDesc: "Renders chests, beds, signs as baked models. Massive FPS gain near storage.",
    description: "Enhanced Block Entities (EBE) reduces block entity rendering time by converting them to use baked block models instead of entity models. This makes rendering chests, beds, signs, shulker boxes and other block entities much faster, particularly noticeable when you have many chests in a storage room.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 84,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 20, max: 120, avg: 45 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Best Graphics"],
    popularity: 82,
    downloadUrl: "https://modrinth.com/mod/ebe",
    installInstructions: "Requires Fabric and Sodium. Place in mods folder. Makes a noticeable difference in storage rooms and villages.",
    tags: ["rendering", "block-entities", "chests", "fps"],
    featured: false,
    dependencies: ["Fabric API", "sodium"]
  },
  {
    id: "fastquit",
    name: "FastQuit",
    icon: "🚪",
    shortDesc: "Return to the title screen instantly while world saves in background.",
    description: "FastQuit allows you to return to the title screen immediately when quitting a world, while the world continues saving in the background. This eliminates the frustrating wait when closing worlds, which is especially long on Android devices with slower storage.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 60,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 71,
    downloadUrl: "https://modrinth.com/mod/fastquit",
    installInstructions: "Drop in mods folder. No configuration needed. Makes quitting worlds significantly faster.",
    tags: ["utility", "quality-of-life", "loading", "saving"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "clumps",
    name: "Clumps",
    icon: "✨",
    shortDesc: "Groups XP orbs together. Reduces entity count and improves FPS.",
    description: "Clumps groups XP orbs together into a single entity, reducing the number of entities in the world and improving performance. This is especially noticeable when killing many mobs or mining ore, where hundreds of XP orbs can spawn and dramatically reduce FPS.",
    versions: ["1.12", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "Forge", "NeoForge"],
    category: "logic",
    performanceRating: 72,
    memoryUsage: "low",
    memoryMB: -16,
    fpsGain: { min: 5, max: 60, avg: 20 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Battery Saver"],
    popularity: 79,
    downloadUrl: "https://modrinth.com/mod/clumps",
    installInstructions: "Place in mods folder. Works on all major loaders. Most noticeable during mob grinding or heavy mining.",
    tags: ["entities", "xp", "orbs", "performance"],
    featured: false,
    dependencies: []
  },
  {
    id: "spark",
    name: "Spark",
    icon: "🔍",
    shortDesc: "Performance profiler. Identify exactly what's lagging your game.",
    description: "Spark is a performance profiling mod for Minecraft. It helps identify what's causing performance issues by providing detailed CPU profiling, memory reporting, and real-time performance monitoring. While not a performance mod itself, it helps you diagnose and fix performance problems.",
    versions: ["1.8", "1.12", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "Forge", "NeoForge"],
    category: "utility",
    performanceRating: 55,
    memoryUsage: "neutral",
    memoryMB: 8,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 83,
    downloadUrl: "https://modrinth.com/mod/spark",
    installInstructions: "Drop in mods folder. Use /spark profiler start to begin profiling. Share results at spark.lucko.me for analysis.",
    tags: ["profiling", "debug", "utility", "diagnostic"],
    featured: false,
    dependencies: []
  }
,
  {
    id: "indium",
    name: "Indium",
    icon: "\ud83c\udf08",
    shortDesc: "Restores mod-added renderer compatibility removed by Sodium.",
    description: "Indium is a small compatibility addon for Sodium that restores the Fabric Rendering API hooks that Sodium removes. It's required by many mods that add custom block/item rendering (like various decoration mods) to work correctly alongside Sodium.",
    versions: ["1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 20,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 0, max: 5, avg: 2 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 70,
    downloadUrl: "https://modrinth.com/mod/indium",
    installInstructions: "Required alongside Sodium if you use mods that add custom block/item models. Place in mods folder.",
    tags: ["compatibility", "rendering", "sodium-addon"],
    featured: false,
    dependencies: ["sodium", "Fabric API"]
  },
  {
    id: "iris",
    name: "Iris",
    icon: "\ud83c\udf1f",
    shortDesc: "Shader pack support built on top of Sodium's fast rendering engine.",
    description: "Iris is a modern shader pack loader compatible with most OptiFine shader packs, built to work alongside Sodium. It brings dramatically improved visuals (dynamic lighting, shadows, reflections) while keeping much of Sodium's performance advantage, though shaders are inherently demanding on mobile GPUs.",
    versions: ["1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 55,
    memoryUsage: "high",
    memoryMB: 120,
    fpsGain: { min: -40, max: 10, avg: -15 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 10,
    minRAM: 4,
    goals: ["Best Graphics"],
    popularity: 88,
    downloadUrl: "https://modrinth.com/mod/iris",
    installInstructions: "Requires Sodium. Place in mods folder, then select a shader pack from Options > Video > Shaders. Heavy on battery/thermals on mobile.",
    tags: ["shaders", "rendering", "graphics"],
    featured: true,
    dependencies: ["sodium", "Fabric API"]
  },
  {
    id: "embeddium",
    name: "Embeddium",
    icon: "\ud83d\udd37",
    shortDesc: "A Sodium-based rendering engine port for NeoForge and Forge.",
    description: "Embeddium brings the rendering optimizations of Sodium to NeoForge and Forge modpacks, since Sodium itself only supports Fabric/Quilt. Essential if your modpack requires Forge-only mods but you still want Sodium-level FPS gains.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Forge", "NeoForge"],
    category: "rendering",
    performanceRating: 92,
    memoryUsage: "low",
    memoryMB: -48,
    fpsGain: { min: 60, max: 200, avg: 110 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 2,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 80,
    downloadUrl: "https://modrinth.com/mod/embeddium",
    installInstructions: "Place in mods folder for Forge/NeoForge installs. Acts as a drop-in replacement for vanilla rendering, similar to Sodium.",
    tags: ["rendering", "forge", "fps", "essential"],
    featured: true,
    dependencies: []
  },
  {
    id: "oculus",
    name: "Oculus",
    icon: "\ud83d\udc41\ufe0f",
    shortDesc: "Iris-equivalent shader support for Forge/NeoForge modpacks.",
    description: "Oculus ports Iris's shader pack support to Forge and NeoForge, letting you run OptiFine-format shaders on top of Embeddium. Demanding on mobile hardware but offers the best visual fidelity available for modded Java Edition.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Forge", "NeoForge"],
    category: "rendering",
    performanceRating: 50,
    memoryUsage: "high",
    memoryMB: 120,
    fpsGain: { min: -40, max: 10, avg: -15 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 10,
    minRAM: 4,
    goals: ["Best Graphics"],
    popularity: 68,
    downloadUrl: "https://modrinth.com/mod/oculus",
    installInstructions: "Requires Embeddium. Place in mods folder, select shaders in Video Settings.",
    tags: ["shaders", "forge", "rendering", "graphics"],
    featured: false,
    dependencies: ["embeddium"]
  },
  {
    id: "rubidium",
    name: "Rubidium",
    icon: "\ud83d\udc8e",
    shortDesc: "Older Sodium port for Forge, predecessor to Embeddium.",
    description: "Rubidium was the original community port of Sodium's rendering optimizations to Forge, predating Embeddium. Still used in some older modpacks, though most newer Forge/NeoForge setups have migrated to Embeddium for continued support.",
    versions: ["1.16", "1.18", "1.19"],
    loaders: ["Forge"],
    category: "rendering",
    performanceRating: 88,
    memoryUsage: "low",
    memoryMB: -40,
    fpsGain: { min: 50, max: 180, avg: 100 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 2,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 58,
    downloadUrl: "https://modrinth.com/mod/rubidium",
    installInstructions: "Place in mods folder for older Forge installs. Consider Embeddium instead for actively-updated modpacks.",
    tags: ["rendering", "forge", "legacy", "fps"],
    featured: false,
    dependencies: []
  },
  {
    id: "vulkanmod",
    name: "VulkanMod",
    icon: "\ud83d\udd3a",
    shortDesc: "Replaces OpenGL with a Vulkan renderer for major FPS gains on supported GPUs.",
    description: "VulkanMod rewrites Minecraft's rendering pipeline to use the Vulkan graphics API instead of OpenGL, often resulting in dramatically better frame times on devices with good Vulkan driver support. Standalone alternative to Sodium \u2014 the two should not be used together.",
    versions: ["1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 90,
    memoryUsage: "low",
    memoryMB: -50,
    fpsGain: { min: 50, max: 250, avg: 120 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 10,
    minRAM: 3,
    goals: ["Maximum FPS"],
    popularity: 65,
    downloadUrl: "https://modrinth.com/mod/vulkanmod",
    installInstructions: "Standalone renderer \u2014 do not install alongside Sodium. Requires a GPU/driver with solid Vulkan support; results vary by Android GPU vendor.",
    tags: ["rendering", "vulkan", "fps", "experimental"],
    featured: false,
    dependencies: []
  },
  {
    id: "starlight",
    name: "Starlight",
    icon: "\ud83d\udca1",
    shortDesc: "Rewrites the lighting engine for massively faster chunk lighting updates.",
    description: "Starlight completely rewrites Minecraft's lighting engine, fixing long-standing lighting bugs while making lighting updates dramatically faster. This reduces stutter when placing/breaking blocks and speeds up chunk loading significantly.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "logic",
    performanceRating: 86,
    memoryUsage: "low",
    memoryMB: -20,
    fpsGain: { min: 10, max: 40, avg: 20 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 78,
    downloadUrl: "https://modrinth.com/mod/starlight",
    installInstructions: "Place in mods folder. No configuration needed. Conflicts with Phosphor \u2014 use one or the other.",
    tags: ["lighting", "logic", "performance", "chunks"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "phosphor",
    name: "Phosphor",
    icon: "\ud83d\udd6f\ufe0f",
    shortDesc: "Legacy lighting engine optimizer, mostly superseded by Starlight.",
    description: "Phosphor was an earlier lighting engine optimization mod for Minecraft. While effective, it has largely been superseded by Starlight, which offers larger gains and also fixes lighting bugs. Useful only on older MC versions where Starlight isn't available.",
    versions: ["1.12", "1.16"],
    loaders: ["Fabric", "Forge"],
    category: "logic",
    performanceRating: 60,
    memoryUsage: "low",
    memoryMB: -15,
    fpsGain: { min: 5, max: 20, avg: 10 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 40,
    downloadUrl: "https://modrinth.com/mod/phosphor",
    installInstructions: "Use only on older Minecraft versions. On 1.18+, install Starlight instead.",
    tags: ["lighting", "legacy", "performance"],
    featured: false,
    dependencies: []
  },
  {
    id: "lazydfu",
    name: "LazyDFU",
    icon: "\ud83e\uddb4",
    shortDesc: "Skips redundant data fixer initialization, cutting game launch time.",
    description: "LazyDFU defers and skips unnecessary initialization of Minecraft's Data Fixer Upper system at startup, which can shave several seconds off launch time \u2014 especially noticeable on slower Android storage and CPUs.",
    versions: ["1.16", "1.17", "1.18"],
    loaders: ["Fabric", "Quilt"],
    category: "logic",
    performanceRating: 45,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Balanced", "Battery Saver"],
    popularity: 55,
    downloadUrl: "https://modrinth.com/mod/lazydfu",
    installInstructions: "Place in mods folder. Purely reduces startup time, no in-game performance change.",
    tags: ["startup", "loading", "logic"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "smoothboot",
    name: "Smooth Boot",
    icon: "\ud83e\udd7e",
    shortDesc: "Reduces CPU priority spikes during world/game startup for smoother boot.",
    description: "Smooth Boot adjusts thread priorities during Minecraft's startup sequence to prevent the game from monopolizing the CPU, reducing stutter and system slowdowns while the game is loading \u2014 helpful on devices that also run background apps.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20"],
    loaders: ["Fabric", "Forge"],
    category: "logic",
    performanceRating: 35,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Battery Saver", "Balanced"],
    popularity: 42,
    downloadUrl: "https://modrinth.com/mod/smooth-boot",
    installInstructions: "Place in mods folder. Effect is limited to the loading phase.",
    tags: ["startup", "cpu", "logic"],
    featured: false,
    dependencies: []
  },
  {
    id: "bobby",
    name: "Bobby",
    icon: "\ud83d\uddfa\ufe0f",
    shortDesc: "Caches distant chunks client-side to fake higher render distance.",
    description: "Bobby caches previously-loaded chunks on disk so they can still be rendered when you move away, simulating a much higher render distance than the server actually sends \u2014 without the memory and network cost of truly loading those chunks.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20"],
    loaders: ["Fabric", "Quilt"],
    category: "memory",
    performanceRating: 65,
    memoryUsage: "neutral",
    memoryMB: 10,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 9,
    minRAM: 3,
    goals: ["Best Graphics", "Balanced"],
    popularity: 60,
    downloadUrl: "https://modrinth.com/mod/bobby",
    installInstructions: "Requires Fabric API. Place in mods folder; configure max render distance in the config file. Server-side multiplayer only.",
    tags: ["chunks", "render-distance", "multiplayer"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "sodiumextra",
    name: "Sodium Extra",
    icon: "\u2795",
    shortDesc: "Adds extra video/HUD options on top of Sodium's settings menu.",
    description: "Sodium Extra extends Sodium's options screen with additional toggles for HUD elements, animations, and minor visual effects, giving more fine-grained control for squeezing extra performance out of low-end devices.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 30,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 0, max: 5, avg: 2 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 50,
    downloadUrl: "https://modrinth.com/mod/sodium-extra",
    installInstructions: "Requires Sodium. Place in mods folder. New options appear in the Sodium video settings screen.",
    tags: ["sodium-addon", "settings", "rendering"],
    featured: false,
    dependencies: ["sodium", "Fabric API"]
  },
  {
    id: "reesessodiumoptions",
    name: "Reese's Sodium Options",
    icon: "\ud83c\udf9b\ufe0f",
    shortDesc: "Restyles and reorganizes Sodium's video settings menu.",
    description: "Reese's Sodium Options reorganizes Sodium's video settings into clearer categories with improved layout, making it easier to find and tweak the specific options that matter most for mobile performance tuning.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 10,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 38,
    downloadUrl: "https://modrinth.com/mod/reeses-sodium-options",
    installInstructions: "Requires Sodium. Purely a UI/UX improvement, no direct performance gain.",
    tags: ["sodium-addon", "ui", "settings"],
    featured: false,
    dependencies: ["sodium", "Fabric API"]
  },
  {
    id: "continuity",
    name: "Continuity",
    icon: "\ud83e\uddf5",
    shortDesc: "Adds connected textures and emissive texture support compatible with Sodium.",
    description: "Continuity implements the connected textures and emissive textures resource pack formats (similar to OptiFine's CTM) in a way that's compatible with Sodium's rendering pipeline, letting you use many OptiFine-style texture packs.",
    versions: ["1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 15,
    memoryUsage: "neutral",
    memoryMB: 5,
    fpsGain: { min: -3, max: 0, avg: -1 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 2,
    goals: ["Best Graphics"],
    popularity: 48,
    downloadUrl: "https://modrinth.com/mod/continuity",
    installInstructions: "Requires Sodium and Indium for full compatibility. Place in mods folder; works with compatible resource packs automatically.",
    tags: ["textures", "resource-packs", "sodium-addon"],
    featured: false,
    dependencies: ["sodium", "indium", "Fabric API"]
  },
  {
    id: "appleskin",
    name: "AppleSkin",
    icon: "\ud83c\udf4e",
    shortDesc: "Shows food saturation/exhaustion info in the HUD. Tiny footprint.",
    description: "AppleSkin adds useful food-related HUD information (saturation, exhaustion, hunger restored by items) to the hunger bar and tooltips. It's a lightweight quality-of-life mod that costs essentially nothing in performance.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "Forge", "NeoForge"],
    category: "general",
    performanceRating: 5,
    memoryUsage: "neutral",
    memoryMB: 2,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 66,
    downloadUrl: "https://modrinth.com/mod/appleskin",
    installInstructions: "Place in mods folder. No configuration needed; HUD updates automatically.",
    tags: ["hud", "food", "quality-of-life"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "alternatecurrent",
    name: "Alternate Current",
    icon: "\ud83d\udd0c",
    shortDesc: "Rewrites redstone dust calculations for faster, more accurate updates.",
    description: "Alternate Current reimplements Minecraft's redstone wire update logic to be both faster and more consistent, eliminating most redstone-related lag spikes in builds with heavy redstone contraptions.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20"],
    loaders: ["Fabric", "Quilt"],
    category: "logic",
    performanceRating: 55,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 2, max: 20, avg: 8 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 44,
    downloadUrl: "https://modrinth.com/mod/alternate-current",
    installInstructions: "Place in mods folder. Most beneficial in redstone-heavy worlds and farms.",
    tags: ["redstone", "logic", "performance"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "chunky",
    name: "Chunky",
    icon: "\ud83e\uddf1",
    shortDesc: "Pre-generates world chunks in the background to avoid in-game stutter.",
    description: "Chunky lets you pre-generate chunks around spawn or a defined area ahead of time, so you don't experience the FPS dips and stutter that come from generating new terrain on the fly while exploring.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Forge", "NeoForge"],
    category: "utility",
    performanceRating: 30,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 2,
    goals: ["Balanced"],
    popularity: 52,
    downloadUrl: "https://modrinth.com/mod/chunky",
    installInstructions: "Place in mods folder. Run /chunky start to begin pre-generating chunks around your world.",
    tags: ["worldgen", "utility", "chunks"],
    featured: false,
    dependencies: []
  },
  {
    id: "betterbiomeblend",
    name: "Better Biome Blend",
    icon: "\ud83c\udfa8",
    shortDesc: "Smarter biome color blending that's faster than vanilla's wide blend radius.",
    description: "Better Biome Blend optimizes how grass/water/foliage colors blend across biome borders, giving smoother gradients than vanilla's blend setting while costing noticeably less performance at high blend radii.",
    versions: ["1.17", "1.18", "1.19", "1.20"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 20,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 1, max: 8, avg: 3 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 33,
    downloadUrl: "https://modrinth.com/mod/better-biome-blend",
    installInstructions: "Place in mods folder. Adjust blend radius in mod config for the best perf/quality tradeoff.",
    tags: ["biomes", "rendering", "performance"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "nochunkcacheinvalidation",
    name: "No Chunk Cache Invalidation",
    icon: "\ud83d\uddc3\ufe0f",
    shortDesc: "Prevents unnecessary chunk render cache resets, reducing micro-stutter.",
    description: "No Chunk Cache Invalidation patches a vanilla inefficiency where chunk render caches get invalidated more often than necessary, which can cause small but frequent stutters. This mod prevents the redundant cache resets.",
    versions: ["1.17", "1.18", "1.19", "1.20"],
    loaders: ["Fabric"],
    category: "logic",
    performanceRating: 18,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 1, max: 5, avg: 2 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 22,
    downloadUrl: "https://modrinth.com/mod/no-chunk-cache-invalidation",
    installInstructions: "Place in mods folder. Small, focused fix with no configuration.",
    tags: ["chunks", "logic", "micro-optimization"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "distanthorizons",
    name: "Distant Horizons",
    icon: "\ud83c\udfd4\ufe0f",
    shortDesc: "Renders far-away terrain as low-detail LODs for huge render distances.",
    description: "Distant Horizons adds a level-of-detail (LOD) system that renders distant terrain in simplified form far beyond your normal render distance, giving the illusion of seeing for miles at a fraction of the performance cost of actually loading that many chunks.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Forge", "NeoForge"],
    category: "rendering",
    performanceRating: 60,
    memoryUsage: "high",
    memoryMB: 200,
    fpsGain: { min: -10, max: 30, avg: 10 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 10,
    minRAM: 4,
    goals: ["Best Graphics"],
    popularity: 72,
    downloadUrl: "https://modrinth.com/mod/distanthorizons",
    installInstructions: "Place in mods folder. Configure LOD render distance carefully on low-RAM devices \u2014 it trades RAM for visual range.",
    tags: ["lod", "render-distance", "graphics"],
    featured: false,
    dependencies: []
  },
  {
    id: "cullleslessleaves",
    name: "Cull Less Leaves",
    icon: "\ud83c\udf43",
    shortDesc: "Aggressively culls hidden leaf faces, big FPS win in forests/jungles.",
    description: "Cull Less Leaves applies more aggressive face culling specifically to leaf blocks, which vanilla renders fairly inefficiently. Especially impactful in jungle and forest biomes packed with foliage.",
    versions: ["1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 50,
    memoryUsage: "low",
    memoryMB: -10,
    fpsGain: { min: 15, max: 50, avg: 25 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 46,
    downloadUrl: "https://modrinth.com/mod/cull-less-leaves",
    installInstructions: "Place in mods folder. Pairs well with Sodium and More Culling.",
    tags: ["rendering", "culling", "leaves", "fps"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "fabricapi",
    name: "Fabric API",
    icon: "\ud83e\udde9",
    shortDesc: "Core library required by the vast majority of Fabric mods.",
    description: "Fabric API is the essential library that provides hooks and APIs most Fabric mods build on top of. It isn't a performance mod itself, but almost nothing on this list will load without it.",
    versions: ["1.14", "1.15", "1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 5,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 7,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced", "Best Graphics", "Battery Saver"],
    popularity: 100,
    downloadUrl: "https://modrinth.com/mod/fabric-api",
    installInstructions: "Required dependency \u2014 install this first before any other Fabric mod.",
    tags: ["library", "essential", "dependency"],
    featured: true,
    dependencies: []
  },
  {
    id: "fabriclanguagekotlin",
    name: "Fabric Language Kotlin",
    icon: "\ud83d\udfe3",
    shortDesc: "Adds Kotlin language support, required by mods written in Kotlin.",
    description: "Fabric Language Kotlin bundles the Kotlin standard library and runtime so that Fabric mods written in Kotlin can load. Purely a dependency \u2014 only needed if another installed mod requires it.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 8,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 7,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 55,
    downloadUrl: "https://modrinth.com/mod/fabric-language-kotlin",
    installInstructions: "Only install if another mod's page lists it as a dependency.",
    tags: ["library", "dependency", "kotlin"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "clothconfig",
    name: "Cloth Config API",
    icon: "\ud83e\uddf5",
    shortDesc: "Shared config-screen library used by many popular mods.",
    description: "Cloth Config API provides a reusable in-game config screen framework that many mods rely on instead of building their own settings UI. A pure dependency with no direct performance effect.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 3,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 7,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 62,
    downloadUrl: "https://modrinth.com/mod/cloth-config",
    installInstructions: "Install when prompted by another mod's dependency list.",
    tags: ["library", "dependency", "config"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "modmenu",
    name: "Mod Menu",
    icon: "\ud83d\udccb",
    shortDesc: "In-game menu listing installed mods and their config screens.",
    description: "Mod Menu adds a screen accessible from the main menu that lists all installed mods and provides quick access to each one's configuration screen, making it much easier to manage a large modlist on a phone.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 2,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 7,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 75,
    downloadUrl: "https://modrinth.com/mod/modmenu",
    installInstructions: "Place in mods folder. Access via the new 'Mods' button on the main menu.",
    tags: ["utility", "ui", "mod-management"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "yacl",
    name: "YetAnotherConfigLib",
    icon: "\ud83d\udcd0",
    shortDesc: "Modern, lightweight config-screen library used by newer mods.",
    description: "YetAnotherConfigLib (YACL) is a more modern alternative to Cloth Config for building in-game settings screens. Some newer performance mods, like Sodium itself in recent versions, depend on it for their options menu.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 3,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 7,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 58,
    downloadUrl: "https://modrinth.com/mod/yacl",
    installInstructions: "Install when prompted by another mod's dependency list.",
    tags: ["library", "dependency", "config"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "rei",
    name: "Roughly Enough Items",
    icon: "\ud83d\udcd6",
    shortDesc: "In-game recipe and item browser. Convenient but adds some memory overhead.",
    description: "Roughly Enough Items (REI) lets you browse every item and crafting recipe directly in-game. Extremely convenient for modded survival, though indexing large modpacks does add noticeable memory and load-time overhead.",
    versions: ["1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 10,
    memoryUsage: "high",
    memoryMB: 80,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 2,
    goals: ["Balanced"],
    popularity: 70,
    downloadUrl: "https://modrinth.com/mod/roughly-enough-items",
    installInstructions: "Place in mods folder. On low-RAM devices, consider a lighter alternative if you don't need recipe lookup.",
    tags: ["recipes", "utility", "inventory"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "jei",
    name: "Just Enough Items",
    icon: "\ud83d\udcd7",
    shortDesc: "The Forge/NeoForge equivalent of REI for recipe and item browsing.",
    description: "Just Enough Items (JEI) is the Forge and NeoForge counterpart to REI, providing the same kind of in-game recipe browsing for modpacks built on those loaders.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Forge", "NeoForge"],
    category: "utility",
    performanceRating: 10,
    memoryUsage: "high",
    memoryMB: 80,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 2,
    goals: ["Balanced"],
    popularity: 68,
    downloadUrl: "https://modrinth.com/mod/jei",
    installInstructions: "Place in mods folder for Forge/NeoForge installs.",
    tags: ["recipes", "utility", "forge"],
    featured: false,
    dependencies: []
  },
  {
    id: "lambdynamiclights",
    name: "LambDynamicLights",
    icon: "\ud83d\udd26",
    shortDesc: "Makes held/dropped light sources actually emit light. Small overhead.",
    description: "LambDynamicLights makes torches, glowstone, and other light-emitting items in your hand or on the ground actually cast dynamic light, rather than only when placed as blocks like in vanilla.",
    versions: ["1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "general",
    performanceRating: 5,
    memoryUsage: "neutral",
    memoryMB: 10,
    fpsGain: { min: -3, max: 0, avg: -1 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 2,
    goals: ["Best Graphics"],
    popularity: 54,
    downloadUrl: "https://modrinth.com/mod/lambdynamiclights",
    installInstructions: "Place in mods folder. Toggle dynamic light sources in its config screen.",
    tags: ["lighting", "visual", "quality-of-life"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "fabricskyboxes",
    name: "FabricSkyboxes",
    icon: "\ud83c\udf0c",
    shortDesc: "Adds custom animated skybox support for resource packs.",
    description: "FabricSkyboxes lets resource packs define custom animated skyboxes, mainly used to enable certain OptiFine-style sky resource packs to work on Fabric without OptiFine itself.",
    versions: ["1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 5,
    memoryUsage: "neutral",
    memoryMB: 8,
    fpsGain: { min: -2, max: 0, avg: -1 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 2,
    goals: ["Best Graphics"],
    popularity: 30,
    downloadUrl: "https://modrinth.com/mod/fabricskyboxes",
    installInstructions: "Place in mods folder. Only matters if you use a compatible resource pack.",
    tags: ["skybox", "resource-packs", "visual"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "soundphysicsremastered",
    name: "Sound Physics Remastered",
    icon: "\ud83d\udd0a",
    shortDesc: "Realistic sound occlusion and reverb. Minor CPU cost for audio realism.",
    description: "Sound Physics Remastered simulates realistic sound propagation \u2014 reverb in caves, muffled sound through walls \u2014 for a more immersive audio experience. Adds a small CPU cost for audio processing.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Forge"],
    category: "general",
    performanceRating: 3,
    memoryUsage: "neutral",
    memoryMB: 15,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 2,
    goals: ["Best Graphics"],
    popularity: 40,
    downloadUrl: "https://modrinth.com/mod/sound-physics-remastered",
    installInstructions: "Place in mods folder. Purely audio \u2014 no FPS impact, slight CPU overhead.",
    tags: ["audio", "immersion", "visual"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "xaerosminimap",
    name: "Xaero's Minimap",
    icon: "\ud83e\udded",
    shortDesc: "Lightweight, highly popular minimap. Minimal performance cost.",
    description: "Xaero's Minimap is one of the most widely used minimap mods, showing a compact map overlay with waypoints and entity radar. Built to be efficient and add very little overhead even on weaker devices.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Forge", "NeoForge"],
    category: "utility",
    performanceRating: 5,
    memoryUsage: "neutral",
    memoryMB: 15,
    fpsGain: { min: -2, max: 0, avg: -1 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 85,
    downloadUrl: "https://modrinth.com/mod/xaeros-minimap",
    installInstructions: "Place in mods folder. Works standalone, no other mods required.",
    tags: ["minimap", "navigation", "utility"],
    featured: false,
    dependencies: []
  },
  {
    id: "xaerosworldmap",
    name: "Xaero's World Map",
    icon: "\ud83d\uddfa\ufe0f",
    shortDesc: "Full-screen companion map to Xaero's Minimap.",
    description: "Xaero's World Map adds a full-screen, zoomable map view that complements Xaero's Minimap, useful for planning routes and marking bases across large explored areas.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Forge", "NeoForge"],
    category: "utility",
    performanceRating: 3,
    memoryUsage: "neutral",
    memoryMB: 20,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 62,
    downloadUrl: "https://modrinth.com/mod/xaeros-world-map",
    installInstructions: "Works best alongside Xaero's Minimap, though it can run standalone.",
    tags: ["map", "navigation", "utility"],
    featured: false,
    dependencies: []
  },
  {
    id: "badoptimizations",
    name: "BadOptimizations",
    icon: "\u26a0\ufe0f",
    shortDesc: "Aggressive, experimental micro-optimizations. Use with caution.",
    description: "BadOptimizations applies a collection of aggressive, sometimes risky micro-optimizations to Minecraft's internals for extra FPS. Because the changes are less conservative than mods like Lithium, occasional compatibility issues are more likely.",
    versions: ["1.18", "1.19", "1.20"],
    loaders: ["Fabric"],
    category: "logic",
    performanceRating: 70,
    memoryUsage: "low",
    memoryMB: -10,
    fpsGain: { min: 5, max: 30, avg: 12 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 9,
    minRAM: 2,
    goals: ["Maximum FPS"],
    popularity: 28,
    downloadUrl: "https://modrinth.com/mod/badoptimizations",
    installInstructions: "Place in mods folder. Test thoroughly \u2014 disable first if you encounter crashes after adding new mods.",
    tags: ["experimental", "logic", "fps"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "extremesoundmuffler",
    name: "Extreme Sound Muffler",
    icon: "\ud83d\udd07",
    shortDesc: "Lets you mute or muffle specific sounds to cut audio processing load.",
    description: "Extreme Sound Muffler gives fine control to mute or reduce the volume of specific in-game sounds, which can slightly reduce audio processing overhead and is popular for muting repetitive ambient sounds.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20"],
    loaders: ["Fabric", "Forge"],
    category: "battery",
    performanceRating: 8,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Battery Saver"],
    popularity: 24,
    downloadUrl: "https://modrinth.com/mod/extreme-sound-muffler",
    installInstructions: "Place in mods folder. Configure muted sounds via the in-game menu.",
    tags: ["audio", "battery", "utility"],
    featured: false,
    dependencies: []
  },
  {
    id: "visuality",
    name: "Visuality",
    icon: "\u2728",
    shortDesc: "Visual + minor performance tweaks bundled together, Sodium-compatible.",
    description: "Visuality bundles a handful of small visual enhancements and rendering micro-optimizations designed specifically to be compatible with Sodium, aimed at squeezing a bit more polish and performance out of an already-optimized setup.",
    versions: ["1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 20,
    memoryUsage: "low",
    memoryMB: -5,
    fpsGain: { min: 2, max: 10, avg: 5 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 2,
    goals: ["Balanced", "Best Graphics"],
    popularity: 26,
    downloadUrl: "https://modrinth.com/mod/visuality",
    installInstructions: "Requires Sodium. Place in mods folder.",
    tags: ["rendering", "sodium-addon", "visual"],
    featured: false,
    dependencies: ["sodium", "Fabric API"]
  },
  {
    id: "notenoughanimations",
    name: "Not Enough Animations",
    icon: "\ud83d\udeb6",
    shortDesc: "Adds smoother player animations with negligible performance cost.",
    description: "Not Enough Animations adds extra player model animations (crawling, sitting on stairs, etc.) for a more natural look, implemented efficiently enough to have essentially no measurable FPS impact.",
    versions: ["1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 2,
    memoryUsage: "neutral",
    memoryMB: 3,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Best Graphics"],
    popularity: 44,
    downloadUrl: "https://modrinth.com/mod/not-enough-animations",
    installInstructions: "Place in mods folder. Purely cosmetic, no configuration needed.",
    tags: ["animations", "visual", "cosmetic"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "simplefog",
    name: "SimpleFog",
    icon: "\ud83c\udf2b\ufe0f",
    shortDesc: "Lets you reduce or disable distance fog rendering to save a little FPS.",
    description: "SimpleFog gives direct control over Minecraft's fog rendering, letting you reduce render-distance fog or disable it entirely. On some devices fog calculation carries a small but real GPU cost.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 10,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 1, max: 8, avg: 3 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Battery Saver"],
    popularity: 20,
    downloadUrl: "https://modrinth.com/mod/simplefog",
    installInstructions: "Place in mods folder. Adjust fog settings from its config screen.",
    tags: ["fog", "rendering", "fps"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "optifab",
    name: "OptiFab",
    icon: "\ud83d\udd04",
    shortDesc: "Compatibility shim allowing select OptiFine-only resource packs/mods on Fabric.",
    description: "OptiFab is a compatibility layer that emulates parts of the OptiFine mod API, allowing some OptiFine-dependent resource pack features to function on a Fabric installation without OptiFine itself.",
    versions: ["1.18", "1.19", "1.20"],
    loaders: ["Fabric"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 10,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 2,
    goals: ["Balanced"],
    popularity: 18,
    downloadUrl: "https://modrinth.com/mod/optifab",
    installInstructions: "Only needed for specific OptiFine-format resource packs. Place in mods folder.",
    tags: ["compatibility", "optifine", "utility"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "sinytraconnector",
    name: "Sinytra Connector",
    icon: "\ud83d\udd17",
    shortDesc: "Runs many NeoForge mods directly on a Fabric instance.",
    description: "Sinytra Connector is a compatibility layer that allows a meaningful subset of NeoForge mods to run on top of a Fabric/Quilt installation, useful when you want both Fabric-exclusive performance mods and specific Forge-ecosystem content mods together.",
    versions: ["1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 30,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 9,
    minRAM: 3,
    goals: ["Balanced"],
    popularity: 32,
    downloadUrl: "https://modrinth.com/mod/connector",
    installInstructions: "Requires Fabric API and Forgified Fabric API. Compatibility varies per mod \u2014 check Modrinth's compatible mod list.",
    tags: ["compatibility", "forge", "fabric"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "voxy",
    name: "Voxy",
    icon: "\ud83e\uddca",
    shortDesc: "Alternative LOD/distant terrain renderer, similar goal to Distant Horizons.",
    description: "Voxy is another level-of-detail renderer that lets you see distant terrain at reduced detail far beyond your normal render distance, offering an alternative implementation and feature set to Distant Horizons.",
    versions: ["1.19", "1.20", "1.21"],
    loaders: ["Fabric"],
    category: "rendering",
    performanceRating: 55,
    memoryUsage: "high",
    memoryMB: 180,
    fpsGain: { min: -15, max: 25, avg: 8 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 10,
    minRAM: 4,
    goals: ["Best Graphics"],
    popularity: 24,
    downloadUrl: "https://modrinth.com/mod/voxy",
    installInstructions: "Place in mods folder. Like other LOD mods, tune render distance carefully on limited-RAM devices.",
    tags: ["lod", "render-distance", "rendering"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "lazylanguageloading",
    name: "Lazy Language Loading",
    icon: "\ud83d\udde3\ufe0f",
    shortDesc: "Loads only the language file you actually use, saving startup memory.",
    description: "Lazy Language Loading prevents Minecraft from loading every installed language's translation file into memory at once, instead loading only your selected language \u2014 a small but free memory saving, especially in heavily modded instances.",
    versions: ["1.17", "1.18", "1.19", "1.20"],
    loaders: ["Fabric", "Quilt"],
    category: "memory",
    performanceRating: 10,
    memoryUsage: "low",
    memoryMB: -15,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Battery Saver", "Balanced"],
    popularity: 20,
    downloadUrl: "https://modrinth.com/mod/lazy-language-loading",
    installInstructions: "Place in mods folder. No configuration needed.",
    tags: ["memory", "startup", "logic"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "notelemetry",
    name: "No Telemetry",
    icon: "\ud83d\udeab",
    shortDesc: "Disables Mojang's background telemetry pings to cut network chatter.",
    description: "No Telemetry disables the background telemetry data Minecraft normally sends to Mojang, slightly reducing network activity and avoiding occasional micro-stutter tied to telemetry requests on unstable mobile connections.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "network",
    performanceRating: 5,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Battery Saver"],
    popularity: 22,
    downloadUrl: "https://modrinth.com/mod/no-telemetry",
    installInstructions: "Place in mods folder. No configuration needed.",
    tags: ["network", "privacy", "battery"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "cullparticles",
    name: "Cull Particles",
    icon: "\u2702\ufe0f",
    shortDesc: "Skips rendering particles that are off-screen or fully obstructed.",
    description: "Cull Particles prevents the game from spending render time on particles that are off-screen or completely hidden behind blocks, which adds up in particle-heavy situations like rain, explosions, or potion effects.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "rendering",
    performanceRating: 18,
    memoryUsage: "neutral",
    memoryMB: 0,
    fpsGain: { min: 2, max: 15, avg: 6 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 8,
    minRAM: 1,
    goals: ["Maximum FPS", "Balanced"],
    popularity: 21,
    downloadUrl: "https://modrinth.com/mod/cull-particles",
    installInstructions: "Place in mods folder. No configuration needed.",
    tags: ["particles", "culling", "rendering"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "lithostitched",
    name: "Lithostitched",
    icon: "\ud83e\udea8",
    shortDesc: "Shared worldgen/data library required by some content and optimization mods.",
    description: "Lithostitched is a shared library mod that provides data-driven worldgen and registry features used by several other mods as a dependency. Not user-facing on its own.",
    versions: ["1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt", "NeoForge"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 3,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 7,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 15,
    downloadUrl: "https://modrinth.com/mod/lithostitched",
    installInstructions: "Install only when another mod lists it as a required dependency.",
    tags: ["library", "dependency", "worldgen"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "forgeconfigapiport",
    name: "Forge Config API Port",
    icon: "\ud83c\udf09",
    shortDesc: "Brings Forge's config API to Fabric so cross-loader mods can use it.",
    description: "Forge Config API Port re-implements Forge's configuration API on Fabric, allowing mods originally written against Forge's config system (often via Sinytra Connector) to function correctly.",
    versions: ["1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 3,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 7,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 16,
    downloadUrl: "https://modrinth.com/mod/forge-config-api-port",
    installInstructions: "Install only when prompted as a dependency, typically alongside Sinytra Connector.",
    tags: ["library", "dependency", "compatibility"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "betterf3",
    name: "Better F3",
    icon: "\ud83d\udda5\ufe0f",
    shortDesc: "Cleans up and adds extra info to the F3 debug screen.",
    description: "Better F3 reorganizes Minecraft's F3 debug overlay into clearer sections and adds extra diagnostic info, handy when tuning performance settings and wanting clear FPS/memory readouts at a glance.",
    versions: ["1.17", "1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 1,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 7,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 34,
    downloadUrl: "https://modrinth.com/mod/better-f3",
    installInstructions: "Place in mods folder. Toggle with F3 as usual; layout customizable in config.",
    tags: ["debug", "ui", "utility"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "appleCore_appcore",
    name: "AppleCore",
    icon: "\ud83c\udf4f",
    shortDesc: "Shared food/hunger API library used by AppleSkin and other food mods.",
    description: "AppleCore provides a common API for mods that modify food and hunger mechanics, acting as a shared dependency so multiple food-related mods (including some AppleSkin configurations on Forge) can coexist cleanly.",
    versions: ["1.16", "1.17", "1.18", "1.19", "1.20"],
    loaders: ["Forge", "NeoForge"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 2,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 7,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 20,
    downloadUrl: "https://modrinth.com/mod/applecore",
    installInstructions: "Install only when a food-related mod lists it as a dependency on Forge/NeoForge.",
    tags: ["library", "dependency", "food"],
    featured: false,
    dependencies: []
  },
  {
    id: "autoconfig",
    name: "Auto Config",
    icon: "\u2699\ufe0f",
    shortDesc: "Lightweight alternative config-screen library used by some smaller mods.",
    description: "Auto Config (1.x) is a simple library for automatically generating in-game config screens from annotated Java classes, used by some smaller utility and performance mods instead of Cloth Config or YACL.",
    versions: ["1.16", "1.17", "1.18", "1.19"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 2,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 7,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 14,
    downloadUrl: "https://modrinth.com/mod/auto-config",
    installInstructions: "Install only when prompted as a dependency by another mod.",
    tags: ["library", "dependency", "config"],
    featured: false,
    dependencies: ["Fabric API"]
  },
  {
    id: "owolib",
    name: "owo-lib",
    icon: "\ud83e\udd89",
    shortDesc: "Shared utility library required by several smaller QoL Fabric mods.",
    description: "owo-lib is a general-purpose utility library providing shared UI, networking, and config tooling that a number of smaller Fabric mods (including some light visual/QoL mods) depend on to function.",
    versions: ["1.18", "1.19", "1.20", "1.21"],
    loaders: ["Fabric", "Quilt"],
    category: "utility",
    performanceRating: 0,
    memoryUsage: "neutral",
    memoryMB: 5,
    fpsGain: { min: 0, max: 0, avg: 0 },
    compatibility: { arm64: true, arm32: true, x86: true },
    minAndroid: 7,
    minRAM: 1,
    goals: ["Balanced"],
    popularity: 30,
    downloadUrl: "https://modrinth.com/mod/owo-lib",
    installInstructions: "Install only when another mod lists owo-lib as a required dependency.",
    tags: ["library", "dependency", "utility"],
    featured: false,
    dependencies: ["Fabric API"]
  }
];

// Mod categories metadata
const MOD_CATEGORIES = {
  rendering: { label: "Rendering", icon: "🎨", color: "#818cf8" },
  memory:    { label: "Memory",    icon: "🧠", color: "#c084fc" },
  logic:     { label: "Game Logic",icon: "⚙️", color: "#fb923c" },
  worldgen:  { label: "World Gen", icon: "🌍", color: "#34d399" },
  network:   { label: "Network",   icon: "🌐", color: "#60a5fa" },
  battery:   { label: "Battery",   icon: "🔋", color: "#4ade80" },
  utility:   { label: "Utility",   icon: "🔧", color: "#f87171" },
  general:   { label: "General",   icon: "✨", color: "#22c55e" }
};

const MC_VERSIONS = ["1.21", "1.20", "1.19", "1.18", "1.17", "1.16", "1.12"];
const MOD_LOADERS = ["Fabric", "Quilt", "NeoForge", "Forge"];
const LAUNCHERS   = ["Mojo Launcher", "PojavLauncher", "Official Launcher", "Other"];
const ANDROID_VERSIONS = ["14", "13", "12", "11", "10", "9", "8"];
const RAM_OPTIONS = ["1 GB", "2 GB", "3 GB", "4 GB", "6 GB", "8 GB+"];
const CPU_ARCHS   = ["ARM64 (64-bit)", "ARM32 (32-bit)", "x86"];
const GPUS        = ["Adreno", "Mali", "PowerVR", "Other"];
const PERF_GOALS  = ["Maximum FPS", "Balanced", "Best Graphics", "Battery Saver"];

// ── Favorites (persisted in localStorage) ─────────────────────
const Favorites = (() => {
  const KEY = "mojoboost_favorites";
  function getAll() {
    try { return JSON.parse(localStorage.getItem(KEY)) || []; }
    catch (e) { return []; }
  }
  function has(id) { return getAll().includes(id); }
  function toggle(id) {
    const favs = getAll();
    const idx = favs.indexOf(id);
    if (idx === -1) favs.push(id); else favs.splice(idx, 1);
    localStorage.setItem(KEY, JSON.stringify(favs));
    return favs.includes(id);
  }
  return { getAll, has, toggle };
})();

// ── Helpers ─────────────────────────────────────────────────
function getModById(id) {
  return MODS_DB.find(m => m.id === id);
}

// Resolves a dependency entry (which may be an internal mod id, like
// "sodium", or an external/library name, like "Fabric API") into a
// display-friendly object.
function resolveDependency(dep) {
  const internal = getModById(dep);
  if (internal) {
    return { label: internal.name, id: internal.id, external: false };
  }
  return { label: dep, id: null, external: true };
}

function initScrollReveal() {
  const items = document.querySelectorAll(".mod-card, .reveal");
  if (!("IntersectionObserver" in window)) return;
  const io = new IntersectionObserver((entries) => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        entry.target.classList.add("revealed");
        io.unobserve(entry.target);
      }
    });
  }, { threshold: 0.05 });
  items.forEach(el => io.observe(el));
}

// ── Mod card rendering (used by mods.html and mod-detail.html) ─
function renderModCard(mod) {
  const isFav = Favorites.has(mod.id);
  const fpsLabel = mod.fpsGain.avg > 0 ? `+${mod.fpsGain.avg} FPS` : "Utility";
  const loaderTags = mod.loaders.slice(0, 3).map(l => `<span class="tag tag-loader">${l}</span>`).join("");
  const memLabel = mod.memoryMB < 0 ? `${mod.memoryMB} MB` : mod.memoryMB === 0 ? "Neutral" : `+${mod.memoryMB} MB`;

  let depsHtml = "";
  if (mod.dependencies && mod.dependencies.length > 0) {
    const depChips = mod.dependencies.map(dep => {
      const r = resolveDependency(dep);
      const cls = r.external ? "tag-loader" : "tag-version";
      return `<span class="tag ${cls}" title="${r.external ? 'External/library dependency' : 'Required mod'}">🔗 ${r.label}</span>`;
    }).join("");
    depsHtml = `
      <div class="mod-deps">
        <span class="mod-deps-label">Requires:</span>
        <div class="mod-tags">${depChips}</div>
      </div>`;
  }

  return `
    <div class="card mod-card" onclick="location.href='mod-detail.html?id=${mod.id}'">
      <div class="mod-card-header">
        <div class="mod-icon">${mod.icon}</div>
        <div class="mod-card-info">
          <div class="mod-name">${mod.name}</div>
          <div class="mod-version">${mod.versions[mod.versions.length - 1]}+ • ${MOD_CATEGORIES[mod.category]?.label || mod.category}</div>
        </div>
        <button class="mod-card-fav ${isFav ? "active" : ""}" onclick="event.stopPropagation(); this.classList.toggle('active', Favorites.toggle('${mod.id}')); if(typeof updateFavCount==='function') updateFavCount(); if(typeof renderMods==='function' && typeof favsOnly!=='undefined' && favsOnly) renderMods();">
          ${isFav ? "★" : "☆"}
        </button>
      </div>
      <div class="mod-desc">${mod.shortDesc}</div>
      <div class="mod-tags">
        ${loaderTags}
        <span class="tag tag-fps">${fpsLabel}</span>
        <span class="tag tag-mem">${memLabel}</span>
      </div>
      ${depsHtml}
      <div class="mod-card-footer">
        <div class="mod-perf-bar"><div class="mod-perf-fill" style="width:${mod.performanceRating}%"></div></div>
        <div class="mod-perf-label">${mod.performanceRating}%</div>
      </div>
    </div>`;
}

// Export for use in other scripts
if (typeof module !== 'undefined') module.exports = { MODS_DB, MOD_CATEGORIES, MC_VERSIONS, MOD_LOADERS, LAUNCHERS, ANDROID_VERSIONS, RAM_OPTIONS, CPU_ARCHS, GPUS, PERF_GOALS, Favorites, renderModCard, getModById };

